---
title: "FruitFly Study"
author: "Group"
date: "2023-11-01"
output: 
 pdf_document:
   keep_tex: true
geometry: left=0.5in,right=0.5in,top=0.5in,bottom=0.5in
urlcolor: blue
header-includes:
  - \usepackage{subfig}
---

```{r setupFiles, include = FALSE}

# Setting Document Options
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center"
)

# Add additional packages by name to the following list
packages <- c("tidyverse", "knitr",
"kableExtra", "car", "psych", "parameters","Rgraphviz","hasseDiagram","multcompView") 
lapply(
  X = packages,
  FUN = library,
  character.only = TRUE
)

# Loading Helper Files and Setting Global Options
source("https://raw.github.com/neilhatfield/STAT461/master/rScripts/ANOVATools.R")
options("contrasts" = c("contr.sum", "contr.poly"))

```


```{r}
# Read In CSV file
fruitFly <- read.csv("fruitflies.csv")
# Convert Condition to Factor
fruitFly$condition <- as.factor(fruitFly$condition)
#AOV for FF data
flyModel <- aov(
  formula = longevity ~ condition,
  data = fruitFly,
  na.action = "na.omit"
  )
```

```{r}
ggplot(data = fruitFly, aes(x = longevity)) + geom_histogram() + ggtitle("Fruitfly Longevity") + xlab("Longevity (Days per Fly)") + ylab("Occurences") + labs(caption = "Figure 1: Fruitfly Longevity by Occurence")

```
```{r}
# Modern Table
parameters::model_parameters(
model = flyModel,
effectsize_type = c("eta", "omega", "epsilon") # Effect sizes
) %>%
knitr::kable(
digits = 4,
col.names = c(
"Source", "SS", "df", "MS", "F", "p-value",
"Eta Sq.", "Omega Sq.", "Epsilon Sq."),
caption = "Modern ANOVA Table for Fruit Fly Data",
booktabs = TRUE,
align = c("l", rep("c", 8))
) %>%
kableExtra::kable_styling(
font_size = 10,
latex_options = c("HOLD_position"))

```

```{r}
pointEst <- dummy.coef(flyModel)
# pointEst # Look at the output of pointEst so you know in what order the estimates appear
pointEst <- unlist(pointEst)
names(pointEst) <- c("Grand Mean", "Null","One Preg","One Virgin","Eight Preg", "Eight Virgin")
data.frame("Estimate" = pointEst) %>%
knitr::kable(
digits = 4,
caption = "Point Estimates from the Fruit Fly Study",
booktabs = TRUE,
align = "c"
) %>%
kableExtra::kable_styling(
font_size = 15,
latex_options = c("HOLD_position")
)
```

```{r}
# Convert the TukeyHSD results to a data frame
flyPairs <- emmeans::emmeans(
object = flyModel, # Your aov/lm object
specs = pairwise ~ condition, # Creates all pairs of the levels of the factor listed
adjust = "tukey", # How you want to control the error rate
level = 0.99 # 1 - Your overall Type I Error Rate
)
## Make a professional looking table
knitr::kable(
x = flyPairs$contrasts, # Grab the appropriate sub-object
digits = 3,
caption = "Pairwise Post Hoc Comparison via Tukey HSD",
col.names = c("Pair", "Difference", "SE", "DF", "t", "p-value"),
align = "lccccc",
booktabs = TRUE
) %>%
kableExtra::kable_styling(
bootstrap_options = c("condensed", "boardered"),
font_size = 12,
latex_options = c("HOLD_position")
)

```
```{r}
modelLabels <- c("1 Fly Mating 1", "5 Factor 4", "125 (days per fly) 120")
modelMatrix <- matrix(
  data = c(FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE),
  nrow = 3,
  ncol = 3,
  byrow = FALSE
)
hasseDiagram::hasse(
 data = modelMatrix,
 labels = modelLabels
)
```

```{r}
# One Way Assumptions
# Homoscedasticity 
ggplot(data = fruitFly, aes(x = condition, y = flyModel$residuals)) + geom_point()

# QQ Plot
car::qqPlot(
x = flyModel$residuals,
distribution = "norm",
envelope = 0.90,
id = FALSE,
pch = 20,
ylab = "Residuals"
)

# Pattern
ggplot(
data = data.frame(
residuals = flyModel$residuals,
index = 1:length(flyModel$residuals)
),
mapping = aes(x = index, y = residuals)
) +
geom_point(size = 1.5) +
geom_line() +
theme_bw() +
geom_hline(
yintercept = 0,
linetype = "dashed",
color = "red"
) +
xlab("Measurement order") +
ylab("Residuals")


```
```{r}
multcompBoxplot(
  formula = longevity ~ condition,
  data = fruitFly,
  compFn = "TukeyHSD",
  plotList = list(
    boxplot = list(fig = c(0, 0.85, 0, 1)),
    multcompLetters = list(
      fig = c(0.8, 0.9, 0.1, 0.9),
      fontsize = 12,
      fontface = "bold"
    )
  )
)
# Still can't figure out how to add all the labels
# Note order of variables on y-axis
#EightVirgin
#EightPreg
#OnePreg
#Null
#OneVirgin

```


\newpage
# Code Appendix

```{r codeAppendix, ref.label = knitr::all_labels(), echo = TRUE, eval = FALSE}

```
