---
title: "461 Final"
author: "Group"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setupFiles, include = FALSE}
# This template file is based off of a template created by Alex Hayes
# https://github.com/alexpghayes/rmarkdown_homework_template

# Setting Document Options
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center"
)

# Add additional packages by name to the following list
packages <- c("tidyverse", "knitr", "rstatix","kableExtra") 
lapply(
  X = packages,
  FUN = library,
  character.only = TRUE
)

# Loading Helper Files and Setting Global Options ----
options(knitr.kable.NA = "")
options("contrasts" = c("contr.sum", "contr.poly"))
source("https://raw.github.com/neilhatfield/STAT461/master/rScripts/ANOVATools.R")

source("https://raw.github.com/neilhatfield/STAT461/master/rScripts/shadowgram.R")


```
```{r dataIN}
# Australia Only Cricket Data ---
cricketData <- read.csv('cricketData.csv')

# Change names for fucntionality
names(cricketData) <- c('Year', 'Location', 'Outcome', 'Type')

cricketData <- cricketData %>%
  mutate(Outcome = ifelse((Outcome=='Win'), "Win", "Non-win"))

# Mutate Home/Away Ratio
cricketData <- cricketData %>%
  group_by(Year) %>%
  mutate(homeRatio = (sum(Location == 'Home')/((sum(Location == 'Away')) + sum(Location == 'Home'))))

# Mutate Win percent ---
cricketData <- cricketData %>%
  group_by(Year, Type) %>%
  mutate(winPercent = (sum(Outcome == 'Win')/((sum(Outcome == 'Win')) + sum(Outcome == 'Non-win'))))



# Convert to Factor ---
cricketData$Location <- as.factor(cricketData$Location)
cricketData$Outcome <- as.factor(cricketData$Outcome)
cricketData$Type <- as.factor(cricketData$Type)


# Attempt Transformation ---
cricketData$winTransformed <- (cricketData$winPercent)^2

cricketData <- cricketData %>%
  dplyr::select(Year, Type, homeRatio, winPercent, winTransformed) %>%
  distinct()


```
```{r sampleStats}
#| tab.cap = "Descriptive Statistics"
# Descriptive statistics on win % by Type ----
winStats <- psych::describeBy(
  x = cricketData$winPercent,
  group = cricketData$Type,
  na.rm = TRUE,
  skew = TRUE,
  ranges = TRUE,
  quant = c(0.25, 0.75),
  IQR = FALSE,
  mat = TRUE,
  digits = 4
)

winStats %>%
  tibble::remove_rownames() %>%
  tibble::column_to_rownames(
    var = "group1"
  ) %>%
  dplyr::select(
    n, min, Q0.25, median, Q0.75, max, mad, mean, sd, skew, kurtosis
  ) %>%
  knitr::kable(
    caption = "Summary Statistics for Win % by Type of Match",
    digits = 3,
    format.args = list(big.mark = ","),
    align = rep('c', 11),
    col.names = c("n", "Min", "Q1", "Median", "Q3", "Max", "MAD", "SAM", "SASD",
                  "Sample Skew", "Sample Ex. Kurtosis"),
    booktabs = TRUE
  )  %>%
  kableExtra::kable_styling(
    font_size = 12,
    latex_options = c("scale_down", "HOLD_position")
  )

```
```{r homewinScatter}
#| fig.cap = "Plot of Home Game Percent vs Adjusted Win Percentage"
cricketData %>%
  ggplot(aes(x = homeRatio, y = winTransformed, color = Type)) + geom_point() + xlab("Win Percentage Sqaured") +ylab("Percent of Games Played at Home") + ggtitle('Home Games vs Wins')
```
```{r}
#| fig.cap = "Shadowgram of Adjusted Win Percentage",
#| fig.pos = "H",
#| fig.height = 2.75

# Create a shadowgram of the distances ----
shadowgram(
  dataVec = cricketData$winTransformed * 100,
  label = "Distance (cm)",
  layers = 70,
  aStep = 7,
  color = "blue"
)
```
```{r aovFit}
# Define AOV for cricketModel ---
cricketModel <- aov(
formula = winTransformed ~ Year + Type + homeRatio,
data = cricketData,
na.action = "na.omit"
)
# Model for homogeneity ---
cricketModel <- aov(
formula = winTransformed ~ Year + Type*homeRatio,
data = cricketData,
na.action = "na.omit"
)

```
```{r linCov}
#| fig.cap = "Linearity Covariate Test",
#| fig.pos = "H",
#| fig.height = 2.75

ggplot(
data = cricketData,
mapping = aes(
y = winTransformed,
x = homeRatio
)
) +
geom_point(size = 2) +
geom_smooth( # Adds a smoother function's graph
inherit.aes = FALSE,
mapping = aes(x = homeRatio, y = winTransformed),
method = "lm", # Fit a Linear Model
formula = y ~ x, # Specifies the form of the "linear" model
color = "black",
linetype = "dashed",
se = FALSE
) +
theme_bw() +
xlab("Percent of Home Games") +
ylab("Win Percent (Adjusted)")
```

```{r assumCheck1}
#| fig.sub = "QQ Plot"
## Step 1: send the data through the Mahalanobis function
outlierDetection <- rstatix::mahalanobis_distance(cricketData)
## Step 2: OPTIONAL--reattach the factor
outlierDetection <- cbind(
outlierDetection,
factor = cricketData$Type
)
## Step 3: Make a scatter plot
ggplot(
data = outlierDetection,
mapping = aes(
y = winTransformed,
x = homeRatio,
shape = is.outlier,
color = factor
)
) +
geom_point(size = 3) +
theme_bw() +
xlab("Percent of Home Games") +
ylab("Win Percent (Adjusted)") +
labs(
color = "Type of Match",
shape = "Potential Outlier"
)
```
```{r assumCheck2}
#| fig.cap = "Homogeneity of Slopes"
# Demo Code for Assessing Homogeneity of Slopes in Keyboarding Pain Study ----
ggplot(
data = cricketData,
mapping = aes(
y = winTransformed,
x = homeRatio,
color = Type,
shape = Type
)
) +
geom_point(size = 2) +
geom_smooth(
method = "lm", # See notes below
mapping = aes(y = predict(cricketModel)),
formula = y ~ x,
se = FALSE
) +
theme_bw() +
xlab("Percent of Home Games") +
ylab("Win Percent (Adjusted)") +
labs(
color = "Type of Match",
shape = "Type of Match"
)
```
```{r gausRes}
# Demo Code for QQ plot in Keyboarding Pain Study ----
car::qqPlot(
x = residuals(cricketModel),
distribution = "norm",
envelope = 0.90,
id = FALSE,
pch = 20,
ylab = "Residuals (Win % Adj.)"
)
```
```{r tukey}
# Generate the Tukey-Anscombe plot ----
ggplot(
  data = data.frame(
    residuals = residuals(cricketModel),
    fitted = fitted.values(cricketModel)
  ),
  mapping = aes(x = fitted, y = residuals)
) +
  geom_point(size = 2) +
  geom_hline(
    yintercept = 0,
    linetype = "dashed",
    color = "grey50"
  ) +
  geom_smooth(
    formula = y ~ x,
    method = stats::loess,
    method.args = list(degree = 1),
    se = FALSE,
    linewidth = 0.5
  ) +
  theme_bw() +
  xlab("Fitted values (Adj. Win %)") +
  ylab("Residuals (Adj. Win %)")
```

```{r assumCheck3}
#| fig.cap = "Independence of Observation Scatter Plot",
#| fig.pos = "H",
#| fig.show = "hold"
## Assess Independence of Observations ---
 
ggplot(
data = data.frame(
residuals = cricketModel$residuals,
index = 1:length(cricketModel$residuals)
),
mapping = aes(x = index, y = residuals)
) +
geom_point(size = 1.5) +
geom_line() +
theme_bw() +
geom_hline(
yintercept = 0,
linetype = "dashed",
color = "red"
) +
xlab("Measurement order") +
ylab("Residuals")


```
```{r omnibus}
#| fig.cap = "Omnibus Output for Cricket Model"
# Omnibus Test/Modern ANCOVA Table ----
parameters::model_parameters(
model = cricketModel,
effectsize_type = c("eta", "omega", "epsilon")
) %>%
dplyr::mutate( #Fixing the Parameter (Source) Column's values
Parameter = dplyr::case_when(
Parameter == "homeRatio" ~ "Percent of Games at Home",
Parameter == "Type" ~ "Type of Cricket Match",
Parameter == "Type:homeRatio" ~ "Type:Home Interaction",
TRUE ~ Parameter
)
) %>%
dplyr::mutate(
p = ifelse(
test = is.na(p),
yes = NA,
no = pvalRound(p)
)
) %>%
knitr::kable(
digits = 4,
col.names = c("Source", "SS", "df", "MS", "F", "p-value",
"Partial Eta Sq.", "Partial Omega Sq.", "Partial Epsilon Sq."),
caption = "ANOVA Table for Cricket Home Games Study",
align = c('l',rep('c',8)),
booktab = TRUE
) %>%
kableExtra::kable_styling(
bootstrap_options = c("striped", "condensed"),
font_size = 12,
latex_options = c("scale_down", "HOLD_position")
)
```
```{r pointEst}
## Type
emmOutKey <- emmeans::emmeans(
object = cricketModel,
specs = pairwise ~ Type,
adjust = "tukey",
level = 0.9
)
## Point Estimates
as.data.frame(emmOutKey$emmeans) %>%
knitr::kable(
digits = 4,
col.names = c("Match Type", "Marginal Mean","SE", "DF",
"Lower Bound","Upper Bound"),
caption = "Marginal Means-Tukey 90\\% Adjustment",
align = c("l", rep("c", 5)),
booktabs = TRUE
) %>%
kableExtra::kable_styling(
bootstrap_options = c("striped", "condensed"),
font_size = 12,
latex_options = c("HOLD_position")
)
```
```{r contrast}
as.data.frame(emmOutKey$contrasts) %>%
knitr::kable(
digits = 4,
col.names = c("Comparison", "Difference","SE", "DF",
"t Statistic","p-value"),
caption = "Marginal Means-Tukey 90\\% Adjustment",
align = c("l", rep("c", 5)),
booktabs = TRUE
) %>%
kableExtra::kable_styling(
bootstrap_options = c("striped", "condensed"),
font_size = 12,
latex_options = c("HOLD_position")
)
```
```{r postHoc}
## Keyboarding Study
as.data.frame(
emmeans::eff_size(
object = emmOutKey,
sigma = sigma(cricketModel),
edf = df.residual(cricketModel)
)
) %>%
dplyr::mutate(
ps = probSup(effect.size),
.after = effect.size
) %>%
dplyr::select(contrast, effect.size, ps) %>%
knitr::kable(
digits = 3,
col.names = c("Keyboard Comparison", "Cohen's d", "Probability of Superiority"),
align = "lccc",
caption = "Effect Sizes for Match Type",
booktab = TRUE
) %>%
kableExtra::kable_styling(
bootstrap_options = c("striped", "condensed"),
font_size = 12,
latex_options = "HOLD_position"
)

```



```{r codeAppendix, ref.label = knitr::all_labels(), echo = TRUE, eval = FALSE}

```
